version: "3.3"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_instance
    restart: unless-stopped
    expose:
      - "27017"
    # ports:
    #   - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: >
      mongod 
      --setParameter internalQueryCacheMaxEntriesPerCollection=5000
      --setParameter collectionSamplingLogIntervalSeconds=300
      --setParameter storageEngineConcurrentReadTransactions=128
      --setParameter storageEngineConcurrentWriteTransactions=128
      --quiet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - PORT=${PORT}
    container_name: app
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "${PORT}"
    ports:
      - "9229:9229" # Debug port
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      
  test:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - PORT=${PORT}
    container_name: test
    env_file:
      - .env
    command: ["npm", "run", "test:coverage:unmocked"]
    depends_on:
      - mongo
    volumes:
      - ./coverage:/app/backend/coverage
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_https
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx-entrypoint/nginx-entrypoint.sh:/nginx-entrypoint-inside-container.sh
      - ./nginx/certs:/etc/ssl
    entrypoint: ["/nginx-entrypoint-inside-container.sh"]
    command: ["nginx", "-g", "daemon off;"]
    environment:
      - PORT=${PORT}
    networks:
      - app_network
    depends_on:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongo_data:
    driver: local

networks:
  app_network:
    driver: bridge
